name: "[Pull-Request] Build & Test"
on: [ pull_request ]
jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        name: Checkout repository
      - name: Build images
        run: docker build -t dorfjungs/wordpress-breeze:testing -f dockerfile .

